### ISSUE TITLE
Update default Python package authors

### ISSUE THREAD

**Issue by benoit74** [openzim/hatch-openzim#2]
Should we update the default Python package authors, that are then used in Pypi metadata for instance.

For instance at https://pypi.org/project/ted2zim/:
![image](https://github.com/openzim/hatch-openzim/assets/7102089/6e9fdd14-1ead-49b1-9059-09599c4fc56f)

For now it is: `[{"name": "Kiwix", "email": "dev@kiwix.org"}]`

@kelson42 this is a question for you for now, I will implement it afterwards

**Comment by kelson42** [comment]
I have no strong opinion. As default value. Why not, but nicer if it can be updated to the real authors.

**Comment by rgaudin** [comment]
@kelson42 it can be updated but the point of this tool is that we update the least possible. So the question is : should be be openZIM by default or Kiwix?

**Comment by kelson42** [comment]
@rgaudin put Kiwix

**Comment by benoit74** [comment]
What is the proper email address to use for openZIM then? (I don't know which aliases are in place)

**Comment by rgaudin** [comment]
Use `dev@openzim.org`, it redirects to `dev@kiwix.org`

**Comment by benoit74** [comment]
I propose to do even better:
- since we detect the repository URL, we also know what is the Github organization ; I propose to set author + first keyword automatically based on Github organization:
  - if Github organization is openzim or unknown, then the author is `openZIM`/`dev@openzim.org` and the first keyword is `openzim`
  - if Github organization is kiwix or offspot, then the author is `Kiwix`/`dev@kiwix.org` and the first keyword is `kiwix`
- I will also add new parameters:
  - `organization`: "force" the organization (no more detection based on Github repository URL)
  - `additional_authors`: just like `additional_keywords`, but for authors
