### ISSUE TITLE
Build hook: do not reinstall file if already present

### ISSUE THREAD

**Issue by benoit74** [openzim/hatch-openzim#3]
Currently, the build plugin checks if file to install is already present. If so, it deletes it and re-download the asset.

This is not very efficient and we should probably switch to another strategy where the asset is downloaded only if not already present.

This is fine because:
- in CI Docker builds, assets will always be missing and hence re-downloaded
- on the local developer machine:
  - the developer usually does not want to re-download the asset at every build
  - should the developer want to update the asset, he just has to clean his local folders
  - the limitation / pain point is when the developer has explicitly updated the asset version in `openzim.toml`, the asset will still not be updated if the developer does not clean his local folder ; we can probably live with it

@rgaudin are you in line with this PoV? do you have any suggestion especially regarding last limitation / pain point?

**Comment by rgaudin** [comment]
I'm not sure I understand completely but:

- reinstall of env is **very frequent** during devel. If it means re-downloading assets each time, it's a problem.
- manual cleaning of env to re-trigger the download seems OK. If it proves frustrating, we can improve the system later or add a command that cleans it
